pool:
  name: Hosted Ubuntu 1604

trigger:
  branches:
    include:
    - master

pr: none

steps:
- task: Docker@0
  displayName: 'Build an image'

- task: Docker@0
  displayName: 'Run an image'
  inputs:
    action: 'Run an image'
    envVars: |
     organisation=$(env.organisation)
     credentials=$(env.credentials)
    detached: false
